#!/bin/sh

cryptname="${1}"
trap stop_udev EXIT

stop_udev() {
    # Stop udev from initramfs, as the real daemon from rootfs will be restarted
    udevadm control --exit
}

# Start udev from initramfs
/lib/systemd/systemd-udevd --daemon --resolve-names=never

# Clean up our console
clear

# Synchronize filesystems before luksSuspend 
sync

# Suspend root device
[ -z "${cryptname}" ] || cryptsetup luksSuspend "${cryptname}"

# Suspend the system
echo mem > /sys/power/state

# Resume root device
[ -z "${cryptname}" ] ||
    while ! cryptsetup luksResume "${cryptname}"; do sleep 2; done

