#!/bin/sh

cryptname="${1}"

# Start udev from initramfs
/lib/systemd/systemd-udevd --daemon --resolve-names=never &>/dev/null

# run dummy cryptsetup to make sure we have all the needed kernel modules
# loaded before doing an actual suspend
[ -z "${cryptname}" ] || cryptsetup luksOpen "${cryptname}" --test-passphrase &>/dev/null || :

# Synchronize filesystems before luksSuspend 
sync

# Suspend root device
[ -z "${cryptname}" ] || cryptsetup luksSuspend "${cryptname}"

# Suspend the system
echo mem > /sys/power/state

# Resume root device
[ -z "${cryptname}" ] ||
    while ! cryptsetup luksResume "${cryptname}"; do sleep 2; done
