#!/bin/sh -e

PREREQS=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/lib/debian-luks-suspend/encrypt-on-suspend /bin

# vim: set ft=sh ts=4 sw=4 et:
